openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API for user authentication with email OTP verification and password reset.

servers:
  - url: http://localhost:5000

paths:
  /auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, phone, password, confirmPassword]
              properties:
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: OTP sent to email
        '400':
          description: Validation error
        '500':
          description: Server error

  /auth/verify-otp:
    post:
      summary: Verify user's email using OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, otp]
              properties:
                email:
                  type: string
                otp:
                  type: string
      responses:
        '200':
          description: Email verified
        '400':
          description: Invalid or expired OTP
        '404':
          description: User not found

  /auth/resend-otp:
    post:
      summary: Resend OTP for email verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
      responses:
        '200':
          description: OTP resent
        '400':
          description: Invalid request
        '500':
          description: Server error

  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Access and refresh tokens
        '401':
          description: Email not verified or user not found
        '403':
          description: Invalid credentials

  /auth/refresh-token:
    post:
      summary: Refresh JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token]
              properties:
                token:
                  type: string
      responses:
        '200':
          description: New access and refresh tokens
        '401':
          description: Token not provided
        '403':
          description: Invalid refresh token

  /auth/forgot-password:
    post:
      summary: Request OTP to reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
      responses:
        '200':
          description: OTP sent to email
        '404':
          description: User not found
        '500':
          description: Server error

  /auth/reset-password:
    post:
      summary: Reset password using OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, otp, newPassword, confirmNewPassword]
              properties:
                email:
                  type: string
                otp:
                  type: string
                newPassword:
                  type: string
                confirmNewPassword:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid or expired OTP
        '404':
          description: User not found

  /profile:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved
        '401':
          description: Unauthorized

  /profile/update-user:
    put:
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                bio:
                  type: string
                dob:
                  type: string
                  format: date
                bloodgroup:
                  type: string
                gender:
                  type: string
                  enum: [Male, Female, Other]
                profession:
                  type: string
                profilePicture:
                  type: string
                  format: uri
      responses:
        '200':
          description: Profile updated successfully
        '400':
          description: Invalid data
        '401':
          description: Unauthorized

  /profile/change-password:
    put:
      summary: Change user password
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [oldPassword, newPassword]
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password updated successfully
        '400':
          description: Invalid current password
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
