paths:
  /:
    get:
      tags:
        - Home
      summary: Get home page data
      description: Retrieves active events and sliders for the home page. Returns up to 10 upcoming events sorted by date and all active sliders sorted by display order.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successfully retrieved home page data
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
                  sliders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Slider'
              example:
                events:
                  - _id: "64a7b8c9d1234567890abcde"
                    title: "Tech Conference 2024"
                    description: "Annual technology conference"
                    imageUrl: "https://example.com/tech-conf.jpg"
                    eventDate: "2024-07-15T00:00:00.000Z"
                    location:
                      city: "San Francisco"
                      state: "CA"
                      country: "USA"
                    category: "Technology"
                    price: 299
                sliders:
                  - _id: "64a7b8c9d1234567890abcdf"
                    title: "Welcome Banner"
                    description: "Main welcome message"
                    imageUrl: "https://example.com/banner.jpg"
                    link: "https://example.com/welcome"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        500:
          $ref: '#/components/responses/InternalServerError'

  /createEvents:
    post:
      tags:
        - Events
      summary: Create a new event
      description: Creates a new event with the provided details. Event date must be today or in the future.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventsData
              properties:
                eventsData:
                  $ref: '#/components/schemas/CreateEventRequest'
            example:
              eventsData:
                title: "Summer Music Festival"
                description: "A three-day outdoor music festival featuring local and international artists"
                imageUrl: "https://example.com/festival.jpg"
                eventDate: "2024-08-15"
                city: "Austin"
                state: "Texas"
                country: "USA"
                category: "Music"
                price: 150
                email: "contact@musicfest.com"
                phone: "+1-555-0123"
                tags: ["music", "festival", "outdoor"]
                isActive: true
      responses:
        201:
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Event created successfully"
                  data:
                    $ref: '#/components/schemas/CreateEventRequest'
        400:
          description: Bad request - validation failed or past date
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - $ref: '#/components/schemas/PastDateError'
                  - $ref: '#/components/schemas/InvalidDateFormatError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        409:
          description: Conflict - event already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictError'
        500:
          $ref: '#/components/responses/InternalServerError'

  /createSliders:
    post:
      tags:
        - Sliders
      summary: Create a new slider
      description: Creates a new slider for the home page carousel. Title and image URL are required fields.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sliderData
              properties:
                sliderData:
                  $ref: '#/components/schemas/CreateSliderRequest'
            example:
              sliderData:
                title: "New Product Launch"
                description: "Discover our latest innovation"
                imageUrl: "https://example.com/product-banner.jpg"
                link: "https://example.com/products/new"
                displayOrder: 1
                isActive: true
      responses:
        201:
          description: Slider created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Slider created successfully"
                  data:
                    $ref: '#/components/schemas/Slider'
        400:
          description: Bad request - validation failed or missing required fields
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - $ref: '#/components/schemas/MissingSliderDataError'
                  - $ref: '#/components/schemas/MissingRequiredFieldsError'
                  - $ref: '#/components/schemas/CastError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        409:
          description: Conflict - slider already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictError'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token required for authentication

  schemas:
    Event:
      type: object
      properties:
        _id:
          type: string
          description: Unique identifier for the event
        title:
          type: string
          description: Event title
        description:
          type: string
          description: Event description
        imageUrl:
          type: string
          format: uri
          description: URL to event image
        eventDate:
          type: string
          format: date-time
          description: Date and time of the event
        location:
          type: object
          properties:
            city:
              type: string
            state:
              type: string
            country:
              type: string
        category:
          type: string
          description: Event category
        price:
          type: number
          description: Event price

    Slider:
      type: object
      properties:
        _id:
          type: string
          description: Unique identifier for the slider
        title:
          type: string
          description: Slider title
        description:
          type: string
          description: Slider description
        imageUrl:
          type: string
          format: uri
          description: URL to slider image
        link:
          type: string
          format: uri
          description: URL that slider links to

    CreateEventRequest:
      type: object
      required:
        - title
        - description
        - imageUrl
        - eventDate
        - city
        - state
        - country
        - category
        - price
        - email
        - phone
      properties:
        title:
          type: string
          description: Event title
          minLength: 1
        description:
          type: string
          description: Event description
          minLength: 1
        imageUrl:
          type: string
          format: uri
          description: URL to event image
        eventDate:
          type: string
          format: date
          description: Event date (YYYY-MM-DD format)
        city:
          type: string
          description: City where event takes place
        state:
          type: string
          description: State where event takes place
        country:
          type: string
          description: Country where event takes place
        category:
          type: string
          description: Event category
        price:
          type: number
          minimum: 0
          description: Event price
        email:
          type: string
          format: email
          description: Contact email for the event
        phone:
          type: string
          description: Contact phone number for the event
        tags:
          type: array
          items:
            type: string
          description: Array of tags for the event
        isActive:
          type: boolean
          description: Whether the event is active
          default: true

    CreateSliderRequest:
      type: object
      required:
        - title
        - imageUrl
      properties:
        title:
          type: string
          description: Slider title
          minLength: 1
        description:
          type: string
          description: Slider description
        imageUrl:
          type: string
          format: uri
          description: URL to slider image
        link:
          type: string
          format: uri
          description: URL that slider links to
        displayOrder:
          type: number
          description: Display order for the slider
          default: 0
        isActive:
          type: boolean
          description: Whether the slider is active
          default: true

    ValidationError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Validation failed"
        errors:
          type: object
          description: Field-specific validation errors
          additionalProperties:
            type: string

    PastDateError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Cannot create event for past dates. Event date must be today or in the future."

    InvalidDateFormatError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Invalid date format for event date"

    ConflictError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Event with this information already exists"

    MissingSliderDataError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Slider data is required"

    MissingRequiredFieldsError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Title and image URL are required fields"

    CastError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Invalid data type for field: displayOrder"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          description: Error message

  responses:
    UnauthorizedError:
      description: Authentication token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Unauthorized access"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal server error"
              error:
                type: string
                description: Error details